# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del objeto')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización del objeto')),
                ('comment', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr.Member')),
            ],
            options={
                'ordering': ('creation_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del objeto')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización del objeto')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del objeto')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización del objeto')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.Customer')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_manager', to='hr.Member')),
                ('members', models.ManyToManyField(related_name='projects', to='hr.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del objeto')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización del objeto')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('deadline', models.DateField(default=None, null=True)),
                ('flow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.FlowStep')),
                ('members', models.ManyToManyField(related_name='tasks', to='hr.Member')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='flowstep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_steps', to='project.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.Task'),
        ),
    ]
