# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default='ES', on_delete=django.db.models.deletion.CASCADE, to='location.Country'),
        ),
    ]
